window.Actions = {
  // Damaging attacks
  boulderRoll: {
    name: "Boulder Roll",
    description: "Rolls into a ball and charges at the opponent, dealing heavy damage.",
    type: "stone",
    accuracy: 0.9,
    energyCost: 24,
    cooldownTurns: 1,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "animation", animation: "spin" },
      { type: "stateChange", damage: 24, damageType: "stone" },
      { type: "textMessage", text: "It's {EFFECTIVENESS} effective." },
    ],
  },
  scratch: {
    name: "Scratch",
    description: "Pounce at the enemy and scratch.",
    type: "shadow",
    accuracy: 0.95,
    energyCost: 16,
    cooldownTurns: 0,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "animation", animation: "spin" },
      { type: "stateChange", damage: 22, damageType: "shadow" },
      { type: "textMessage", text: "It's {EFFECTIVENESS} effective." },
    ],
  },
  wingSlap: {
    name: "Wing Slap",
    description: "Slaps the opponent with its wings, dealing moderate damage.",
    type: "fly",
    accuracy: 0.95,
    energyCost: 18,
    cooldownTurns: 0,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "animation", animation: "spin" },
      { type: "stateChange", damage: 21, damageType: "fly" },
      { type: "textMessage", text: "It's {EFFECTIVENESS} effective." },
    ],
  },
  flameBurst: {
    name: "Flame Burst",
    description: "Creates a burst of flames that damages the opponent and has a chance to cause a burn.",
    type: "fire",
    accuracy: 0.92,
    energyCost: 22,
    cooldownTurns: 1,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "animation", animation: "glob", color: "red" },
      { type: "stateChange", damage: 22, damageType: "fire" },
      { type: "textMessage", text: "It's {EFFECTIVENESS} effective." },
    ],
  },
  bubbleBeam: {
    name: "Bubble Beam",
    description: "Fires a beam of bubbles, dealing moderate damage and possibly lowering their speed.",
    type: "water",
    accuracy: 0.95,
    energyCost: 20,
    cooldownTurns: 0,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "animation", animation: "glob", color: "blue" },
      { type: "stateChange", damage: 21, damageType: "water" },
      { type: "textMessage", text: "It's {EFFECTIVENESS} effective." },
    ],
  },
  shadowBolt: {
    name: "Shadow Bolt",
    description: "A bolt of dark energy, dealing heavy damage and possibly causing them to flinch.",
    type: "shadow",
    accuracy: 0.9,
    energyCost: 24,
    cooldownTurns: 1,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "animation", animation: "glob", color: "purple" },
      { type: "stateChange", damage: 22, damageType: "shadow" },
      { type: "textMessage", text: "It's {EFFECTIVENESS} effective." },
    ],
  },
  blizzard: {
    name: "Blizzard",
    description: "A fierce snowstorm dealing moderate damage and lowering the opponents accuracy.",
    type: "water",
    accuracy: 0.86,
    energyCost: 28,
    cooldownTurns: 2,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "animation", animation: "glob", color: "blue" },
      { type: "stateChange", damage: 24, damageType: "water" },
      { type: "textMessage", text: "It's {EFFECTIVENESS} effective." },
    ],
  },
  emberTrail: {
    name: "Ember Trail",
    description: "Scorches the opponent for immediate damage and lingering burn damage.",
    type: "fire",
    accuracy: 0.88,
    energyCost: 26,
    cooldownTurns: 2,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "animation", animation: "glob", color: "red" },
      { type: "stateChange", damage: 18, damageType: "fire" },
      { type: "stateChange", status: { type: "burned", expiresIn: 3 } },
      { type: "textMessage", text: "{TARGET} is burned!" },
    ],
  },
  vineWhip: {
    name: "Vine Whip",
    description: "A quick nature attack that restores a little health to its user.",
    type: "nature",
    accuracy: 0.94,
    energyCost: 20,
    cooldownTurns: 0,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "animation", animation: "spin" },
      { type: "stateChange", damage: 20, damageType: "nature" },
      { type: "stateChange", recover: 8, onCaster: true },
      { type: "textMessage", text: "It's {EFFECTIVENESS} effective." },
    ],
  },
  tidalCrash: {
    name: "Tidal Crash",
    description: "A powerful water strike with a longer recovery window.",
    type: "water",
    accuracy: 0.82,
    energyCost: 34,
    cooldownTurns: 2,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "animation", animation: "glob", color: "blue" },
      { type: "stateChange", damage: 30, damageType: "water" },
      { type: "textMessage", text: "It's {EFFECTIVENESS} effective." },
    ],
  },
  seismicCrash: {
    name: "Seismic Crash",
    description: "Slams the ground and sends a shockwave through the arena.",
    type: "stone",
    accuracy: 0.85,
    energyCost: 30,
    cooldownTurns: 2,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "animation", animation: "quake" },
      { type: "stateChange", damage: 27, damageType: "stone" },
      { type: "textMessage", text: "It's {EFFECTIVENESS} effective." },
    ],
  },
  skyDive: {
    name: "Sky Dive",
    description: "Launches forward on a slicing gust of wind.",
    type: "fly",
    accuracy: 0.9,
    energyCost: 26,
    cooldownTurns: 1,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "animation", animation: "gust" },
      { type: "stateChange", damage: 25, damageType: "fly" },
      { type: "textMessage", text: "It's {EFFECTIVENESS} effective." },
    ],
  },
  cinderCyclone: {
    name: "Cinder Cyclone",
    description: "Whirls embers into a burning spiral that chars the target.",
    type: "fire",
    accuracy: 0.88,
    energyCost: 29,
    cooldownTurns: 2,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "animation", animation: "flare", color: "#ff8a24" },
      { type: "stateChange", damage: 22, damageType: "fire" },
      { type: "stateChange", status: { type: "burned", expiresIn: 2 } },
      { type: "textMessage", text: "{TARGET} is burned!" },
    ],
  },
  riptideRing: {
    name: "Riptide Ring",
    description: "A spinning ring of water crashes into the foe.",
    type: "water",
    accuracy: 0.9,
    energyCost: 24,
    cooldownTurns: 1,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "animation", animation: "surge", color: "#34b3ff" },
      { type: "stateChange", damage: 24, damageType: "water" },
      { type: "textMessage", text: "It's {EFFECTIVENESS} effective." },
    ],
  },
  umbraPounce: {
    name: "Umbra Pounce",
    description: "Leaps from the shadows with a heavy strike.",
    type: "shadow",
    accuracy: 0.9,
    energyCost: 25,
    cooldownTurns: 1,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "animation", animation: "eclipse" },
      { type: "stateChange", damage: 24, damageType: "shadow" },
      { type: "textMessage", text: "It's {EFFECTIVENESS} effective." },
    ],
  },
  thornVolley: {
    name: "Thorn Volley",
    description: "Launches sharp thorns and siphons a little vitality.",
    type: "nature",
    accuracy: 0.92,
    energyCost: 23,
    cooldownTurns: 1,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "animation", animation: "bloom", color: "#63b84d" },
      { type: "stateChange", damage: 20, damageType: "nature" },
      { type: "stateChange", recover: 7, onCaster: true },
      { type: "textMessage", text: "It's {EFFECTIVENESS} effective." },
    ],
  },
  stoneWall: {
    name: "Stone Wall",
    targetType: "friendly",
    description: "Raises a sturdy guard that reduces incoming damage for three turns.",
    energyCost: 20,
    cooldownTurns: 2,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "stateChange", status: { type: "harden", expiresIn: 3 } },
      { type: "textMessage", text: "{CASTER} is protected by stone!" },
    ],
  },

  concussiveSlam: {
    name: "Concussive Slam",
    description: "A crushing impact that may stun the target for one turn.",
    type: "stone",
    accuracy: 0.84,
    energyCost: 30,
    cooldownTurns: 2,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "animation", animation: "quake" },
      { type: "stateChange", damage: 24, damageType: "stone" },
      { type: "stateChange", status: { type: "stunned", expiresIn: 1 } },
      { type: "textMessage", text: "{TARGET} is stunned!" },
      { type: "textMessage", text: "It's {EFFECTIVENESS} effective." },
    ],
  },

  drench: {
    name: "Drench",
    description: "Soaks the target, lowering evasion and increasing water damage taken.",
    type: "water",
    accuracy: 0.93,
    energyCost: 18,
    cooldownTurns: 1,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "animation", animation: "surge", color: "#34b3ff" },
      { type: "stateChange", status: { type: "soaked", expiresIn: 3 } },
      { type: "textMessage", text: "{TARGET} is soaked!" },
    ],
  },

  thornGuard: {
    name: "Thorn Guard",
    targetType: "friendly",
    description: "Wraps the caster in thorns, reflecting part of incoming damage.",
    energyCost: 22,
    cooldownTurns: 2,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "stateChange", status: { type: "thorn-guard", expiresIn: 3 } },
      { type: "textMessage", text: "{CASTER} is covered in thorn guard!" },
    ],
  },

  // Friendly
  harden: {
    name: "Harden",
    targetType: "friendly",
    description: " The animal hardens its body, increasing its defense.",
    energyCost: 14,
    cooldownTurns: 1,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "stateChange", status: { type: "harden", expiresIn: 3 } },
      { type: "textMessage", text: "{CASTER} defense increases!" },
    ],
  },
  revitalize: {
    name: "Revitalize",
    targetType: "friendly",
    description: "The animal imbues itself with revitalizing energy, instantly restoring a large amount of health.",
    energyCost: 26,
    cooldownTurns: 2,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION}!" },
      { type: "stateChange", recover: 22 },
      { type: "textMessage", text: "{CASTER} recovers HP!" },
    ],
  },
  regeneration: {
    name: "Regeneration",
    targetType: "friendly",
    description: "The animal gradually restores its own health over time.",
    energyCost: 18,
    cooldownTurns: 2,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION} on itself!" },
      { type: "stateChange", status: { type: "regen", expiresIn: 3 } },
      { type: "textMessage", text: "{CASTER} will regenerate over time!" },
    ],
  },

  // Items
  item_hayBale: {
    name: "Hay Bale",
    description: "Restores a large amount of health to the farm animal.",
    targetType: "friendly",
    accuracy: 1,
    energyCost: 0,
    cooldownTurns: 0,
    success: [
      { type: "textMessage", text: "{CASTER} eats a {ACTION}!" },
      { type: "stateChange", recover: 50 },
      { type: "textMessage", text: "{CASTER} recovers HP!" },
    ],
  },
  item_flySpray: {
    name: "Fly Spray",
    description: "Remove all current effects on your farm animal.",
    targetType: "friendly",
    accuracy: 1,
    energyCost: 0,
    cooldownTurns: 0,
    success: [
      { type: "textMessage", text: "{CASTER} uses some {ACTION}." },
      { type: "stateChange", status: null },
      { type: "textMessage", text: "{CASTER} removed all effects!" },
    ],
  },
  item_dustBath: {
    name: "Dust Bath",
    description: "Cover the enemy in dust, causing them to be clumsy.",
    accuracy: 0.95,
    energyCost: 0,
    cooldownTurns: 0,
    success: [
      { type: "textMessage", text: "{CASTER} uses {ACTION} on {TARGET}." },
      { type: "stateChange", status: { type: "clumsy", expiresIn: 3 } },
      { type: "textMessage", text: "{TARGET} is stumbling around." },
    ],
  },
};
