import { utils } from "./../../utils.js";

const socialEventCutscene = [
  {
    exclude: "SEEN_SOCIALROOM_SCENE",
    events: [
      { type: "addStoryFlag", flag: "SEEN_SOCIALROOM_SCENE" },
      { type: "stand", who: "npc5", direction: "up", time: 200 },
      { type: "textMessage", text: "Sandy: Please stop this at once, it has gone to far!" },
      { type: "walk", who: "hero", direction: "up" },
      { type: "walk", who: "hero", direction: "up" },
      { type: "walk", who: "hero", direction: "up" },
      { type: "walk", who: "hero", direction: "up" },
      { type: "textMessage", text: "Sandy: Don't you see this is immoral? You are keeping him captive." },
      { type: "walk", who: "npc3", direction: "down" },
      { type: "textMessage", text: "Tony: Immoral?? We are creating the future here!" },
      { type: "stand", who: "npc5", direction: "left", time: 200 },
      { type: "stand", who: "npc5", direction: "right", time: 200 },
      { type: "stand", who: "npc5", direction: "up", time: 100 },
      {
        type: "textMessage",
        text: "Sandy: But the poor man, his family must be worried sick!",
      },
      {
        type: "textMessage",
        text: "Frank: Tony sir, someone is here!",
      },
      { type: "walk", who: "npc4", direction: "down" },
      { type: "walk", who: "npc4", direction: "down" },
      { type: "walk", who: "npc4", direction: "down" },
      { type: "textMessage", text: "Frank: It's that fathers son!" },
      {
        type: "textMessage",
        text: "Tony: Hey kiddo, has your dad contacted you yet? He has been really busy on a new project",
      },
      {
        type: "textMessage",
        text: "Tony: He said he can't wait for you to see what he has done. Says it will change the world.",
      },
      {
        type: "textMessage",
        text: "Sandy: Don't listen to him! Your father has been taken by them",
        faceHero: "npc5",
      },
      { type: "walk", who: "npc3", direction: "left" },
      { type: "walk", who: "npc3", direction: "left" },
      { type: "walk", who: "npc3", direction: "down" },
      { type: "walk", who: "npc3", direction: "down" },
      { type: "textMessage", text: "Tony: No trust me, here take this. You can see him in the Tournment." },
      { type: "walk", who: "npc3", direction: "down" },
      { type: "walk", who: "npc3", direction: "right" },
      { type: "stand", who: "npc3", direction: "down", time: 200 },
      { type: "textMessage", text: "* Tony hands you an invitation to the tournment. *" },
      { type: "addStoryFlag", flag: "ARENA_INVITATION" },
      { type: "addStoryFlag", flag: "CHAPTER_1_MID_STARTED" },
      {
        type: "advanceQuestStep",
        questId: "quest_rescue_dad_ch1",
        step: 3,
        nextStep: "Take the invitation to the Hay Tournament gate in the north-east district.",
      },
      { type: "walk", who: "npc3", direction: "right" },
      { type: "walk", who: "npc3", direction: "right" },
      { type: "stand", who: "npc5", direction: "left", time: 200 },
      { type: "textMessage", text: "Tony: Sandy I'm going to have to ask you to leave..." },
      { type: "textMessage", text: "Sandy: How dare you!" },
      { type: "walk", who: "npc5", direction: "down" },
      { type: "walk", who: "npc5", direction: "down" },
      { type: "walk", who: "npc5", direction: "down" },
      { type: "walk", who: "npc5", direction: "down" },
      { type: "walk", who: "npc5", direction: "down" },
      { type: "stand", who: "npc5", direction: "down", time: 80 },
      { type: "walk", who: "npc5", direction: "left" },
      { type: "walk", who: "npc5", direction: "left" },
      { type: "walk", who: "npc5", direction: "down" },
      { type: "walk", who: "npc3", direction: "right" },
      { type: "walk", who: "npc3", direction: "right" },
      { type: "walk", who: "npc3", direction: "right" },
      { type: "walk", who: "npc3", direction: "right" },
      { type: "walk", who: "npc3", direction: "right" },
      { type: "stand", who: "npc3", direction: "right", time: 80 },
      { type: "walk", who: "npc3", direction: "up" },
      { type: "walk", who: "npc3", direction: "up" },
      { type: "walk", who: "npc3", direction: "up" },
      { type: "stand", who: "npc3", direction: "up", time: 80 },
      { type: "walk", who: "npc3", direction: "left" },
      { type: "walk", who: "npc3", direction: "left" },
      { type: "walk", who: "npc3", direction: "left" },
      { type: "walk", who: "npc3", direction: "left" },
      { type: "walk", who: "npc3", direction: "left" },
      { type: "walk", who: "npc3", direction: "left" },
      { type: "stand", who: "npc3", direction: "down", time: 500 },
      { type: "textMessage", text: "Tony: Go see your father Sam, he is waiting." },
    ],
  },
  {
    required: ["SEEN_SOCIALROOM_SCENE"],
    exclude: "CUTSCENE_SANDY_COMPLETE",
    events: [
      { type: "addStoryFlag", flag: "CUTSCENE_SANDY_COMPLETE" },
      {
        type: "textMessage",
        text: "Sandy: Be careful Sam, I don't trust there motives.",
        faceHero: "npc5",
      },
    ],
  },
];

export const SocialClubRoom = {
  id: "SocialClubRoom",
  lowerSrc: "./assets/maps/newmaps/room3_lower.png",
  upperSrc: "./assets/maps/newmaps/room3_upper.png",
  configObjects: {
    hero: {
      type: "Person",
      isPlayerControlled: true,
      src: "./assets/characters/people/hero.png",
      x: utils.withGrid(4),
      y: utils.withGrid(10),
    },
    npc1: {
      type: "Person",
      x: utils.withGrid(9),
      y: utils.withGrid(2),
      src: "./assets/characters/people/blacksmith.png",
      behaviorLoop: [{ type: "stand", direction: "down", time: 1000 }],
    },
    npc2: {
      type: "Person",
      x: utils.withGrid(7),
      y: utils.withGrid(2),
      src: "./assets/characters/people/blacksmith2.png",
      behaviorLoop: [{ type: "stand", direction: "down", time: 1000 }],
    },
    npc3: {
      type: "Person",
      x: utils.withGrid(5),
      y: utils.withGrid(2),
      src: "./assets/characters/people/blacksmith.png",
      behaviorLoop: [{ type: "stand", direction: "down", time: 1000 }],
    },
    npc4: {
      type: "Person",
      x: utils.withGrid(2),
      y: utils.withGrid(2),
      src: "./assets/characters/people/blacksmith2.png",
      behaviorLoop: [{ type: "stand", direction: "right", time: 1000 }],
      talking: [
        {
          required: ["DEFEATED_npc4_OUTSIDELEFT"],
          events: [
            {
              type: "textMessage",
              text: "Wow, I hope the boss can handle this...",
              faceHero: "npc4",
            },
          ],
        },
        {
          events: [
            {
              type: "textMessage",
              text: "Ha, goodluck!",
              faceHero: "npc4",
            },
            { type: "battle", enemyId: "Frank" },
            { type: "addStoryFlag", flag: "DEFEATED_npc4_OUTSIDELEFT" },
          ],
        },
      ],
    },
    npc5: {
      type: "Person",
      x: utils.withGrid(7),
      y: utils.withGrid(6),
      src: "./assets/characters/people/barmaid2.png",
      behaviorLoop: [{ type: "stand", direction: "up", time: 1000 }],
    },
  },
  walls: {
    [utils.asGridCoord(2, 1)]: true,
    [utils.asGridCoord(3, 1)]: true,
    [utils.asGridCoord(4, 1)]: true,
    [utils.asGridCoord(5, 1)]: true,
    [utils.asGridCoord(6, 1)]: true,
    [utils.asGridCoord(7, 1)]: true,
    [utils.asGridCoord(8, 1)]: true,
    [utils.asGridCoord(9, 1)]: true,
    [utils.asGridCoord(10, 1)]: true,
    [utils.asGridCoord(11, 1)]: true,
    [utils.asGridCoord(12, 1)]: true,
    [utils.asGridCoord(1, 2)]: true,
    [utils.asGridCoord(13, 3)]: true,
    [utils.asGridCoord(1, 3)]: true,
    [utils.asGridCoord(13, 4)]: true,
    [utils.asGridCoord(1, 4)]: true,
    [utils.asGridCoord(4, 4)]: true,
    [utils.asGridCoord(5, 4)]: true,
    [utils.asGridCoord(6, 4)]: true,
    [utils.asGridCoord(7, 4)]: true,
    [utils.asGridCoord(8, 4)]: true,
    [utils.asGridCoord(9, 4)]: true,
    [utils.asGridCoord(10, 4)]: true,
    [utils.asGridCoord(13, 5)]: true,
    [utils.asGridCoord(1, 5)]: true,
    [utils.asGridCoord(4, 5)]: true,
    [utils.asGridCoord(5, 5)]: true,
    [utils.asGridCoord(6, 5)]: true,
    [utils.asGridCoord(7, 5)]: true,
    [utils.asGridCoord(8, 5)]: true,
    [utils.asGridCoord(9, 5)]: true,
    [utils.asGridCoord(10, 5)]: true,
    [utils.asGridCoord(13, 6)]: true,
    [utils.asGridCoord(1, 6)]: true,
    [utils.asGridCoord(13, 7)]: true,
    [utils.asGridCoord(1, 7)]: true,
    [utils.asGridCoord(13, 8)]: true,
    [utils.asGridCoord(1, 8)]: true,
    [utils.asGridCoord(13, 9)]: true,
    [utils.asGridCoord(1, 9)]: true,
    [utils.asGridCoord(13, 10)]: true,
    [utils.asGridCoord(1, 10)]: true,
    [utils.asGridCoord(11, 10)]: true,
    [utils.asGridCoord(12, 10)]: true,
    [utils.asGridCoord(1, 11)]: true,
    [utils.asGridCoord(12, 11)]: true,
    [utils.asGridCoord(2, 12)]: true,
    [utils.asGridCoord(3, 12)]: true,
    [utils.asGridCoord(6, 12)]: true,
    [utils.asGridCoord(7, 12)]: true,
    [utils.asGridCoord(8, 12)]: true,
    [utils.asGridCoord(9, 12)]: true,
    [utils.asGridCoord(10, 12)]: true,
    [utils.asGridCoord(11, 12)]: true,
  },
  cutsceneSpaces: {
    /* SocialClubRoom - NPC interactions */
    [utils.asGridCoord(4, 11)]: socialEventCutscene,
    /* SocialClubRoom - NPC interactions end */

    /* SocialClubRoom - Room map changing */
    [utils.asGridCoord(4, 12)]: [
      {
        events: [
          {
            type: "changeMap",
            map: "OutsideRight",
            x: utils.withGrid(6),
            y: utils.withGrid(17),
            direction: "down",
          },
        ],
      },
    ],
    [utils.asGridCoord(5, 12)]: [
      {
        events: [
          {
            type: "changeMap",
            map: "OutsideRight",
            x: utils.withGrid(6),
            y: utils.withGrid(17),
            direction: "down",
          },
        ],
      },
    ],
    /* SocialClubRoom - Room map changing end */
  },
};
